//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSRedefined.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CSLecturer
    {
        public tbl_CSLecturer()
        {
            this.tbl_CSTopic = new HashSet<tbl_CSTopic>();
        }
    
        public int GUID { get; set; }
        public string LecturerNo { get; set; }
        public string Name { get; set; }
        public bool Status { get; set; }
        public int SessionID { get; set; }
        public string Description { get; set; }
    
        public virtual tbl_Session tbl_Session { get; set; }
        public virtual ICollection<tbl_CSTopic> tbl_CSTopic { get; set; }
    }
}
