//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSRedefined.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ConfigUsage
    {
        public int GUID { get; set; }
        public int RoleID { get; set; }
        public int SessionID { get; set; }
        public bool Enabled { get; set; }
        public string Days { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public System.DateTime ToTime { get; set; }
    
        public virtual tbl_Role tbl_Role { get; set; }
        public virtual tbl_Session tbl_Session { get; set; }
    }
}
