//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSRedefined.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PmsUser
    {
        public int GUID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int RoleTypeID { get; set; }
        public bool Status { get; set; }
    
        public virtual tbl_RoleType tbl_RoleType { get; set; }
    }
}
