//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSRedefined.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RoleType
    {
        public tbl_RoleType()
        {
            this.tbl_PmsUser = new HashSet<tbl_PmsUser>();
        }
    
        public int GUID { get; set; }
        public int UserID { get; set; }
        public int RoleAssigned { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tbl_PmsUser> tbl_PmsUser { get; set; }
        public virtual tbl_Role tbl_Role { get; set; }
    }
}
