//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSRedefined.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ConfigLockUser
    {
        public int GUID { get; set; }
        public int RoleID { get; set; }
        public int LockRoleAfter { get; set; }
    
        public virtual tbl_Role tbl_Role { get; set; }
    }
}
