//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSRedefined.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Session
    {
        public tbl_Session()
        {
            this.tbl_ConfigUsage = new HashSet<tbl_ConfigUsage>();
            this.tbl_ConfigUserTopic = new HashSet<tbl_ConfigUserTopic>();
            this.tbl_CSLecturer = new HashSet<tbl_CSLecturer>();
            this.tbl_CSTopic = new HashSet<tbl_CSTopic>();
            this.tbl_ProjectChapter = new HashSet<tbl_ProjectChapter>();
            this.tbl_Student = new HashSet<tbl_Student>();
            this.tbl_StudentActivity = new HashSet<tbl_StudentActivity>();
        }
    
        public int GUID { get; set; }
        public string SessionName { get; set; }
        public string SessionCode { get; set; }
    
        public virtual ICollection<tbl_ConfigUsage> tbl_ConfigUsage { get; set; }
        public virtual ICollection<tbl_ConfigUserTopic> tbl_ConfigUserTopic { get; set; }
        public virtual ICollection<tbl_CSLecturer> tbl_CSLecturer { get; set; }
        public virtual ICollection<tbl_CSTopic> tbl_CSTopic { get; set; }
        public virtual ICollection<tbl_ProjectChapter> tbl_ProjectChapter { get; set; }
        public virtual tbl_RegisteredTopic tbl_RegisteredTopic { get; set; }
        public virtual ICollection<tbl_Student> tbl_Student { get; set; }
        public virtual ICollection<tbl_StudentActivity> tbl_StudentActivity { get; set; }
    }
}
